import { Book } from './types';

export const BOOKS: Book[] = [
  { id: 'gen', name: 'Genesis', namePt: 'Gênesis', chapters: 50 },
  { id: 'exo', name: 'Exodus', namePt: 'Êxodo', chapters: 40 },
  { id: 'lev', name: 'Leviticus', namePt: 'Levítico', chapters: 27 },
  { id: 'num', name: 'Numbers', namePt: 'Números', chapters: 36 },
  { id: 'deu', name: 'Deuteronomy', namePt: 'Deuteronômio', chapters: 34 },
  { id: 'jos', name: 'Joshua', namePt: 'Josué', chapters: 24 },
  { id: 'jdg', name: 'Judges', namePt: 'Juízes', chapters: 21 },
  { id: 'rut', name: 'Ruth', namePt: 'Rute', chapters: 4 },
  { id: '1sa', name: '1 Samuel', namePt: '1 Samuel', chapters: 31 },
  { id: '2sa', name: '2 Samuel', namePt: '2 Samuel', chapters: 24 },
  { id: '1ki', name: '1 Kings', namePt: '1 Reis', chapters: 22 },
  { id: '2ki', name: '2 Kings', namePt: '2 Reis', chapters: 25 },
  { id: '1ch', name: '1 Chronicles', namePt: '1 Crônicas', chapters: 29 },
  { id: '2ch', name: '2 Chronicles', namePt: '2 Crônicas', chapters: 36 },
  { id: 'ezr', name: 'Ezra', namePt: 'Esdras', chapters: 10 },
  { id: 'neh', name: 'Nehemiah', namePt: 'Neemias', chapters: 13 },
  { id: 'est', name: 'Esther', namePt: 'Ester', chapters: 10 },
  { id: 'job', name: 'Job', namePt: 'Jó', chapters: 42 },
  { id: 'psa', name: 'Psalms', namePt: 'Salmos', chapters: 150 },
  { id: 'pro', name: 'Proverbs', namePt: 'Provérbios', chapters: 31 },
  { id: 'ecc', name: 'Ecclesiastes', namePt: 'Eclesiastes', chapters: 12 },
  { id: 'sng', name: 'Song of Solomon', namePt: 'Cântico dos Cânticos', chapters: 8 },
  { id: 'isa', name: 'Isaiah', namePt: 'Isaías', chapters: 66 },
  { id: 'jer', name: 'Jeremiah', namePt: 'Jeremias', chapters: 52 },
  { id: 'lam', name: 'Lamentations', namePt: 'Lamentações', chapters: 5 },
  { id: 'eze', name: 'Ezekiel', namePt: 'Ezequiel', chapters: 48 },
  { id: 'dan', name: 'Daniel', namePt: 'Daniel', chapters: 12 },
  { id: 'hos', name: 'Hosea', namePt: 'Oseias', chapters: 14 },
  { id: 'joe', name: 'Joel', namePt: 'Joel', chapters: 3 },
  { id: 'amo', name: 'Amos', namePt: 'Amós', chapters: 9 },
  { id: 'oba', name: 'Obadiah', namePt: 'Obadias', chapters: 1 },
  { id: 'jon', name: 'Jonah', namePt: 'Jonas', chapters: 4 },
  { id: 'mic', name: 'Micah', namePt: 'Miqueias', chapters: 7 },
  { id: 'nah', name: 'Nahum', namePt: 'Naum', chapters: 3 },
  { id: 'hab', name: 'Habakkuk', namePt: 'Habacuque', chapters: 3 },
  { id: 'zep', name: 'Zephaniah', namePt: 'Sofonias', chapters: 3 },
  { id: 'hag', name: 'Haggai', namePt: 'Ageu', chapters: 2 },
  { id: 'zec', name: 'Zechariah', namePt: 'Zacarias', chapters: 14 },
  { id: 'mal', name: 'Malachi', namePt: 'Malaquias', chapters: 4 },
  { id: 'mat', name: 'Matthew', namePt: 'Mateus', chapters: 28 },
  { id: 'mrk', name: 'Mark', namePt: 'Marcos', chapters: 16 },
  { id: 'luk', name: 'Luke', namePt: 'Lucas', chapters: 24 },
  { id: 'jhn', name: 'John', namePt: 'João', chapters: 21 },
  { id: 'act', name: 'Acts', namePt: 'Atos', chapters: 28 },
  { id: 'rom', name: 'Romans', namePt: 'Romanos', chapters: 16 },
  { id: '1co', name: '1 Corinthians', namePt: '1 Coríntios', chapters: 16 },
  { id: '2co', name: '2 Corinthians', namePt: '2 Coríntios', chapters: 13 },
  { id: 'gal', name: 'Galatians', namePt: 'Gálatas', chapters: 6 },
  { id: 'eph', name: 'Ephesians', namePt: 'Efésios', chapters: 6 },
  { id: 'php', name: 'Philippians', namePt: 'Filipenses', chapters: 4 },
  { id: 'col', name: 'Colossians', namePt: 'Colossenses', chapters: 4 },
  { id: '1th', name: '1 Thessalonians', namePt: '1 Tessalonicenses', chapters: 5 },
  { id: '2th', name: '2 Thessalonians', namePt: '2 Tessalonicenses', chapters: 3 },
  { id: '1ti', name: '1 Timothy', namePt: '1 Timóteo', chapters: 6 },
  { id: '2ti', name: '2 Timothy', namePt: '2 Timóteo', chapters: 4 },
  { id: 'tit', name: 'Titus', namePt: 'Tito', chapters: 3 },
  { id: 'phm', name: 'Philemon', namePt: 'Filemom', chapters: 1 },
  { id: 'heb', name: 'Hebrews', namePt: 'Hebreus', chapters: 13 },
  { id: 'jas', name: 'James', namePt: 'Tiago', chapters: 5 },
  { id: '1pe', name: '1 Peter', namePt: '1 Pedro', chapters: 5 },
  { id: '2pe', name: '2 Peter', namePt: '2 Pedro', chapters: 3 },
  { id: '1jn', name: '1 John', namePt: '1 João', chapters: 5 },
  { id: '2jn', name: '2 John', namePt: '2 João', chapters: 1 },
  { id: '3jn', name: '3 John', namePt: '3 João', chapters: 1 },
  { id: 'jud', name: 'Jude', namePt: 'Judas', chapters: 1 },
  { id: 'rev', name: 'Revelation', namePt: 'Apocalipse', chapters: 22 },
];

export const MOCK_BIBLE_DATA: Record<string, Record<string, string[]>> = {
  'jhn': {
    '1': [
      "In the beginning was the Word, and the Word was with God, and the Word was God.",
      "The same was in the beginning with God.",
      "All things were made by him; and without him was not any thing made that was made.",
      "In him was life; and the life was the light of men.",
      "And the light shineth in darkness; and the darkness comprehended it not.",
      "There was a man sent from God, whose name was John.",
      "The same came for a witness, to bear witness of the Light, that all men through him might believe.",
      "He was not that Light, but was sent to bear witness of that Light.",
      "That was the true Light, which lighteth every man that cometh into the world.",
      "He was in the world, and the world was made by him, and the world knew him not.",
      "He came unto his own, and his own received him not.",
      "But as many as received him, to them gave he power to become the sons of God, even to them that believe on his name:",
      "Which were born, not of blood, nor of the will of the flesh, nor of the will of man, but of God.",
      "And the Word was made flesh, and dwelt among us, (and we beheld his glory, the glory as of the only begotten of the Father,) full of grace and truth."
    ]
  }
};

export const MOCK_BIBLE_DATA_PT: Record<string, Record<string, string[]>> = {
  'jhn': {
    '1': [
      "No princípio era o Verbo, e o Verbo estava com Deus, e o Verbo era Deus.",
      "Ele estava no princípio com Deus.",
      "Todas as coisas foram feitas por ele, e sem ele nada do que foi feito se fez.",
      "Nele estava a vida, e a vida era a luz dos homens.",
      "E a luz resplandece nas trevas, e as trevas não a compreenderam.",
      "Houve um homem enviado de Deus, cujo nome era João.",
      "Este veio para testemunho, para que testificasse da luz, para que todos cressem por ele.",
      "Não era ele a luz, mas veio para que testificasse da luz.",
      "Ali estava a luz verdadeira, que ilumina a todo o homem que vem ao mundo.",
      "Estava no mundo, e o mundo foi feito por ele, e o mundo não o conheceu.",
      "Veio para o que era seu, e os seus não o receberam.",
      "Mas, a todos quantos o receberam, deu-lhes o poder de serem feitos filhos de Deus, aos que creem no seu nome;",
      "Os quais não nasceram do sangue, nem da vontade da carne, nem da vontade do varão, mas de Deus.",
      "E o Verbo se fez carne, e habitou entre nós, e vimos a sua glória, como a glória do unigênito do Pai, cheio de graça e de verdade."
    ]
  }
};
